# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7942f915c9fb9592bb69e6228604170b9c98987e7663175ead96f36c0c0683fdb252251335fa5430f57f743c1a5d67da6164c1dcc28730dcf528ec20bd06bf8b

test:
  secret_key_base: 70a12b4f384a6d13ba178ac8d7368526329a923abaabb01ec8ebe62a259a28542333690fef97586a58b5c5fa04beefd72e6b3bb42733896215d33e92af807f93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
